In [1]:
import geopandas as gpd # type: ignore
import pandas as pd
from pathlib import Path
from tqdm import tqdm

In [5]:

data_path = Path('U:/staff-umbrella/imagesummary/data/Delft_NL/panoids/panoids.geojson')
# data_path = Path('panoids.geojson')
# panoids = gpd.read_file(data_path / 'panoids/panoids.geojson')
panoids = gpd.read_file(data_path)

DriverError: U:\staff-umbrella\imagesummary\data\Delft_NL\panoids.geojson: No such file or directory

In [3]:
# new_db_unsplit = panoids.copy[['year', 'month', 'dist', 'angle', 'path',]]
# new_db = pd.DataFrame(columns=['img_id','year', 'month', 'path', 'geometry', 'dist', 'angle'])

new_db = pd.DataFrame()

for index, row in tqdm(panoids.iterrows(), total=len(panoids)):
	temp_data_a = {'img_id': index, 'img_id_com': index * 4 + 0, 'part_of_img': 'a', 'year': row['year'], 'month': row['month'],
				'path': row['im_side_a'], 'geometry': row['geometry'], 'dist': row['dist'], 'angle': row['angle']}
	temp_data_front = {'img_id': index, 'img_id_com': index * 4 + 1, 'part_of_img': 'front', 'year': row['year'], 'month': row['month'],
					'path': row['im_front'], 'geometry': row['geometry'], 'dist': row['dist'], 'angle': row['angle']}
	temp_data_b = {'img_id': index, 'img_id_com': index * 4 + 2, 'part_of_img': 'b', 'year': row['year'], 'month': row['month'],
				'path': row['im_side_b'], 'geometry': row['geometry'], 'dist': row['dist'], 'angle': row['angle']}
	temp_data_back = {'img_id': index, 'img_id_com': index * 4 + 3, 'part_of_img': 'back', 'year': row['year'], 'month': row['month'],
				   'path': row['im_back'], 'geometry': row['geometry'], 'dist': row['dist'], 'angle': row['angle']}
	
	new_db = pd.concat([new_db, pd.DataFrame([temp_data_a, temp_data_front, temp_data_b, temp_data_back])], ignore_index=True)

new_geo_db = gpd.GeoDataFrame(new_db, geometry='geometry', crs='EPSG:4326')

NameError: name 'panoids' is not defined

In [4]:
display(new_db)

,img_id,part_of_img,year,month,path,geometry,dist,angle
0,0,a,2009,9,image_0_s_a.png,POINT (4.359440875051115 51.97032403643426),21.508589,59.398
1,0,front,2009,9,image_0_f.png,POINT (4.359440875051115 51.97032403643426),21.508589,59.398
2,0,b,2009,9,image_0_s_b.png,POINT (4.359440875051115 51.97032403643426),21.508589,59.398
3,0,back,2009,9,image_0_b.png,POINT (4.359440875051115 51.97032403643426),21.508589,59.398
4,1,a,2014,7,image_1_s_a.png,POINT (4.359418843181012 51.97034580599981),21.983408,63.045
...,...,...,...,...,...,...,...,...
143419,35854,back,2017,6,image_35854_b.png,POINT (4.37250803364355 52.03193840210772),0.044956,-37.232
143420,35855,a,2017,8,image_35855_s_a.png,POINT (4.372547316981993 52.0319609152074),0.387266,-37.232
143421,35855,front,2017,8,image_35855_f.png,POINT (4.372547316981993 52.0319609152074),0.387266,-37.232
143422,35855,b,2017,8,image_35855_s_b.png,POINT (4.372547316981993 52.0319609152074),0.387266,-37.232
143423,35855,back,2017,8,image_35855_b.png,POINT (4.372547316981993 52.0319609152074),0.387266,-37.232

In [6]:
new_geo_db.to_file('image_info.geojson', driver='GeoJSON')

In [7]:
display(gpd.read_file('image_info.geojson'))

,img_id,part_of_img,year,month,path,dist,angle,geometry
0,0,a,2009,9,image_0_s_a.png,21.508589,59.398,POINT (4.35944 51.97032)
1,0,front,2009,9,image_0_f.png,21.508589,59.398,POINT (4.35944 51.97032)
2,0,b,2009,9,image_0_s_b.png,21.508589,59.398,POINT (4.35944 51.97032)
3,0,back,2009,9,image_0_b.png,21.508589,59.398,POINT (4.35944 51.97032)
4,1,a,2014,7,image_1_s_a.png,21.983408,63.045,POINT (4.35942 51.97035)
...,...,...,...,...,...,...,...,...
143419,35854,back,2017,6,image_35854_b.png,0.044956,-37.232,POINT (4.37251 52.03194)
143420,35855,a,2017,8,image_35855_s_a.png,0.387266,-37.232,POINT (4.37255 52.03196)
143421,35855,front,2017,8,image_35855_f.png,0.387266,-37.232,POINT (4.37255 52.03196)
143422,35855,b,2017,8,image_35855_s_b.png,0.387266,-37.232,POINT (4.37255 52.03196)
143423,35855,back,2017,8,image_35855_b.png,0.387266,-37.232,POINT (4.37255 52.03196)

In [12]:
data_path_hoods = Path('cells.geojson')

cells = gpd.read_file(data_path_hoods)

In [13]:
new_cells_db = pd.DataFrame()

for index, row in tqdm(cells.iterrows(), total=len(cells)):
	temp_data = {'neighbourhood_id': index, 'geometry': row['geometry'], 'area': row['area']}
	
	new_cells_db = pd.concat([new_cells_db, pd.DataFrame([temp_data])], ignore_index=True)

new_cells_geo_db = gpd.GeoDataFrame(new_cells_db, geometry='geometry', crs='EPSG:4326')

100%|██████████| 3909/3909 [00:01<00:00, 2424.94it/s]

In [14]:
display(new_cells_geo_db)

,neighbourhood_id,geometry,area
0,0,"POLYGON ((4.32027 52.00985, 4.32100 52.00984, ...",6495.190528
1,1,"POLYGON ((4.32025 52.00907, 4.32098 52.00906, ...",6495.190528
2,2,"POLYGON ((4.32022 52.00829, 4.32095 52.00828, ...",6495.190528
3,3,"POLYGON ((4.32020 52.00751, 4.32093 52.00750, ...",6495.190528
4,4,"POLYGON ((4.32137 52.01022, 4.32210 52.01022, ...",6495.190528
...,...,...,...
3904,3904,"POLYGON ((4.40642 51.96914, 4.40715 51.96913, ...",6495.190528
3905,3905,"POLYGON ((4.40639 51.96836, 4.40712 51.96835, ...",6495.190528
3906,3906,"POLYGON ((4.40637 51.96758, 4.40710 51.96757, ...",6495.190528
3907,3907,"POLYGON ((4.40752 51.96951, 4.40825 51.96950, ...",6495.190528
3908,3908,"POLYGON ((4.40750 51.96873, 4.40823 51.96873, ...",6495.190528

In [15]:
new_cells_geo_db.to_file('neighbourhood_info.geojson', driver='GeoJSON')

In [16]:
display(gpd.read_file('neighbourhood_info.geojson'))

,neighbourhood_id,area,geometry
0,0,6495.190528,"POLYGON ((4.32027 52.00985, 4.32100 52.00984, ..."
1,1,6495.190528,"POLYGON ((4.32025 52.00907, 4.32098 52.00906, ..."
2,2,6495.190528,"POLYGON ((4.32022 52.00829, 4.32095 52.00828, ..."
3,3,6495.190528,"POLYGON ((4.32020 52.00751, 4.32093 52.00750, ..."
4,4,6495.190528,"POLYGON ((4.32137 52.01022, 4.32210 52.01022, ..."
...,...,...,...
3904,3904,6495.190528,"POLYGON ((4.40642 51.96914, 4.40715 51.96913, ..."
3905,3905,6495.190528,"POLYGON ((4.40639 51.96836, 4.40712 51.96835, ..."
3906,3906,6495.190528,"POLYGON ((4.40637 51.96758, 4.40710 51.96757, ..."
3907,3907,6495.190528,"POLYGON ((4.40752 51.96951, 4.40825 51.96950, ..."
3908,3908,6495.190528,"POLYGON ((4.40750 51.96873, 4.40823 51.96873, ..."